#!/usr/bin/env python

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(12, GPIO.OUT)

GPIO.output(12, GPIO.LOW)
time.sleep(0.1)
GPIO.output(12, GPIO.HIGH)
time.sleep(0.5)
print("DMA is reset.")

GPIO.cleanup()
